- packages/java-parser/src/tokens.js
- packages/java-parser/test/bugs-spec.js
The FloatLiteral pattern could now parse scientific notation as 1.0e-10 or 1.e-1
Fix #131
> fix FloatLiteral pattern

- packages/java-parser/scripts/clone-samples.js
- packages/java-parser/test/samples-spec.js
Create function createFailingSampleSpec to only fail after N files fail (it parse all sample files in one single spec)
Related to #128
> feat(tests): create createFailingSampleSpec

- packages/java-parser/src/productions/blocks-and-statements.js
- packages/java-parser/test/samples-spec.js
I started working on test failures on Guava samples. The first I tried to tackle is https://github.com/google/guava/blob/838560034dfaa1afdf51a126afe6b8b8e6cce3dd/android/guava/src/com/google/common/cache/Striped64.java#L216
It seems for me that there were an issue in breakStatement : the semiColon was not consumed. 
(https://docs.oracle.com/javase/specs/jls/se11/html/jls-14.html#jls-BreakStatement)
> fix(parser): fixmissing semicolon consuming in break statement

- packages/java-parser/src/productions/classes.js
- packages/java-parser/test/samples-spec.js
Allow optional `([ArgumentList])` : see https://docs.oracle.com/javase/specs/jls/se11/html/jls-8.html#jls-EnumConstantList
Fix https://github.com/google/guava/blob/838560034dfaa1afdf51a126afe6b8b8e6cce3dd/guava-tests/test/com/google/common/hash/HashTestUtils.java#L95 parsing
> fix(EnumConstant): align EnumConstant rule with the spec

- packages/java-parser/src/productions/classes.js
- packages/java-parser/src/productions/expressions.js
- packages/java-parser/test/samples-spec.js
Use backtracking in dimExprs rule because dims were confused as dimExpr in the parser (https://docs.oracle.com/javase/specs/jls/se11/html/jls-15.html#jls-15.10.1)
Fix parsing of https://github.com/google/guava/blob/838560034dfaa1afdf51a126afe6b8b8e6cce3dd/guava-tests/benchmark/com/google/common/math/StatsBenchmark.java#L149
Include #136 commits to avoid merge conflict in packages/java-parser/test/samples-spec.js
> Fix dim exprs rule

- packages/java-parser/src/tokens.js
I was trying to parse this file https://github.com/jhipster/jhipster/blob/master/jhipster-framework/src/main/java/io/github/jhipster/config/JHipsterDefaults.java#L193, however it failed at line 193 ```int durationInSeconds = 3_600; ``` with the following error:
```
{ [MismatchedTokenException: Expecting --> ';' <-- but found --> '_600' <--]
name: 'MismatchedTokenException',
message: 'Expecting --> \';\' <-- but found --> \'_600\' <--',
token:
{ image: '_600',
startOffset: 4660,
endOffset: 4663,
startLine: 193,
endLine: 193,
startColumn: 38,
endColumn: 41,
tokenTypeIdx: 2,
tokenType:
{ PATTERN: /[a-zA-Z_\\$][a-zA-Z_\\$0-9]*/,
tokenTypeIdx: 2,
CATEGORIES: [],
categoryMatches: [Array],
categoryMatchesMap: [Object],
tokenName: 'Identifier',
isParent: true } },
previousToken:
{ image: '3', …
```
> Fix DecimalLiteral regex

- packages/java-parser/src/productions/interfaces.js
As I was trying to parse the spring-framework repository, this file was failing to parse https://github.com/spring-projects/spring-framework/blob/master/spring-context/src/test/java/org/springframework/context/annotation/PropertySourceAnnotationTests.java#L442 (L442 and L451) due to the metadata content in the annotation. It seems that JAVA accept ElementValueList to end with a comma even though the JAVA specification says otherwise https://docs.oracle.com/javase/specs/jls/se11/html/jls-9.html#jls-ElementValueList.
> Fix annotation: accepting comma as last element in ElementValueList

- packages/java-parser/src/tokens.js
As suggested in (https://github.com/jhipster/prettier-java/pull/145) I've re-opened a PR with only changing the whitespace redefinition.
> Aligned whitespace definition with Java Specs

- packages/java-parser/src/productions/arrays.js
- packages/java-parser/src/productions/classes.js
- packages/java-parser/src/productions/expressions.js
- packages/java-parser/src/productions/interfaces.js
- packages/java-parser/src/productions/names.js
- packages/java-parser/src/productions/packages-and-modules.js
- packages/java-parser/src/productions/types-values-and-variables.js
I this PR I changed the comparison of tokenType with "===" by tokenMatcher as it supports token categories and at the same time it fix #138.
> Using tokenMatcher instead of === to compare tokenType

- packages/java-parser/src/productions/blocks-and-statements.js
Hello, this time I tried to parse the jenkins repository and it failed at this line https://github.com/jenkinsci/jenkins/blob/master/test/src/test/java/hudson/cli/CLITest.java#L268 due to the semicolon at the end of the try with resources. The problem is similar to #142 and can be fixed with a GATE as well.
> Fix try with resources: acception semicolon as last token

- packages/java-parser/test/samples-spec.js
Since we fixed #147, the tests are failing with Guava repository because it expects 8 fails, but the fix reduced the number of fails down to 4.
> Fix the running test

- packages/java-parser/src/productions/packages-and-modules.js
- packages/java-parser/test/bugs-spec.js
Hello, this time the parser failed with https://github.com/thinkaurelius/titan/blob/titan10/titan-all/src/main/java/com/thinkaurelius/titan/graphdb/tinkerpop/plugin/TitanGremlinPlugin.java#L12. This is due to the double semi-colon ```;;``` that is accepted by Java. I did an ad hoc fix that does not look pretty..., another solution would also be to add a big OPTION in "importDeclaration" rule.
But honestly I think ```;;``` is really ugly and I just want to PR the repository to delete the semi-colon :joy:.
> fix imports accept double semi-colon

- packages/java-parser/src/productions/packages-and-modules.js
See https://docs.oracle.com/javase/specs/jls/se11/html/jls-7.html#jls-ModuleDirective
Fix parsing of
```java
module com.client.myservicelient {
provides fr.soat.vending.machine.services.DrinksService
with fr.soat.coffee.maker.CoffeeService;
}
```
> fix(providesModuleDirective parser): parse missing typeName

- packages/java-parser/src/index.js
I have added the comment attachment on tokens in the parser.
Since the cst printer is using the npm java-parser and not the one from the master, can we release a new version ? Since I need the comment attachment to add the support of comment in the cst printer.
> attach comments to tokens

- packages/java-parser/src/productions/packages-and-modules.js
- packages/java-parser/test/bugs-spec.js
The parser fails with the following code (thanks @clement26695  for having found this bug :smile: ) :
```JAVA
@Test
public class Foo{}
```
The parser go to the rule ```packageDeclaration``` instead of ```typeDeclaration``` because both can start with annotation. This can be easily fixed with a Gate and I have not found a way to make it work without it.
> fix annotation in packageDeclaration

- .gitignore
- package.json
- packages/prettier-plugin-java/.gitignore
- packages/prettier-plugin-java/scripts/clone-samples.js
- packages/prettier-plugin-java/scripts/update-test-output.js
- packages/prettier-plugin-java/src/printers/classes.js
- packages/prettier-plugin-java/src/printers/expressions.js
- packages/prettier-plugin-java/src/printers/interfaces.js
- packages/prettier-plugin-java/src/printers/printer-utils.js
- packages/prettier-plugin-java/test/prettify-test.js
- packages/prettier-plugin-java/test/test-utils.js
I have added some repositories to test and it seems that the plugin can now successfully prettify spring-boot and still be semantically valid.
I also added some fixes.
fix #186
> Add test repository

- azure-pipelines.yml
- package.json
- packages/prettier-plugin-java/test/test-utils.js
Here is the Azure Pipelines configuration. It launches the test for node 8.16.0, 10.15.3 and 12.2.0 and launches extended end to end test on jhipster repositories.
related discussions #197
> Azure pipelines

- packages/prettier-plugin-java/src/printers/blocks-and-statements.js
- packages/prettier-plugin-java/test/unit-test/try_catch/_input.java
- packages/prettier-plugin-java/test/unit-test/try_catch/_output.java
Format 
```java
void multiResourceTry() {
try (FirstResource firstResource = new FirstResource(); SecondResource secondResource = new SecondResource()) {
return br.readLine();
} catch (ArithmeticException | ArrayIndexOutOfBoundsException e) {
System.out.println("Warning: Not breaking multi exceptions");
}
}
```
to 
```java
void multiResourceTry() {
try (
FirstResource firstResource = new FirstResource();
SecondResource secondResource = new SecondResource()
) {
return br.readLine();
} catch (ArithmeticException | ArrayIndexOutOfBoundsException e) {
System.out.println("Warning: Not breaking multi exceptions");
}
}
```
> fix(tryWithResourcesStatement): fix printing with multiple resources

- packages/prettier-plugin-java/src/printers/arrays.js
- packages/prettier-plugin-java/src/printers/blocks-and-statements.js
- packages/prettier-plugin-java/src/printers/classes.js
- packages/prettier-plugin-java/src/printers/interfaces.js
- packages/prettier-plugin-java/src/printers/printer-utils.js
The logic to create a curly braces block was duplicated. This PR is to excract this logic to limit code duplication.
The putIntoCurlyBraces function is to print curly braces bloc with correct indentation, and handling empty curly braces block with just an inner comment.
> refactor: extract curly braces blocks logic into printer-utils

- packages/java-parser/src/index.js
- packages/java-parser/src/productions/packages-and-modules.js
- packages/prettier-plugin-java/src/printers/packages-and-modules.js
- packages/prettier-plugin-java/src/printers/prettier-builder.js
- packages/prettier-plugin-java/test/unit-test/comments/comments-only/_input.java
- packages/prettier-plugin-java/test/unit-test/comments/comments-only/_output.java
- packages/prettier-plugin-java/test/unit-test/comments/comments-spec.js
- packages/prettier-plugin-java/test/unit-test/comments/edge/_output.java
The parser fails when given in input only commented code, this is due to the fact that we are attaching comments to token but since there is no token it breaks.
I tried a little "hack" by mocking a token where all comments will attach to it.
> Fix comment only code

- packages/prettier-plugin-java/src/printers/blocks-and-statements.js
- packages/prettier-plugin-java/src/printers/expressions.js
- packages/prettier-plugin-java/src/printers/printer-utils.js
- packages/prettier-plugin-java/test/unit-test/binary_expressions/_output.java
- packages/prettier-plugin-java/test/unit-test/comments/class/_output.java
- packages/prettier-plugin-java/test/unit-test/comments/comments-blocks-and-statements/_input.java
- packages/prettier-plugin-java/test/unit-test/comments/comments-blocks-and-statements/_output.java
- packages/prettier-plugin-java/test/unit-test/expressions/_input.java
- packages/prettier-plugin-java/test/unit-test/expressions/_output.java
Fix the breaking expression discussed [here](https://github.com/jhipster/prettier-java/issues/218)
Example:
input:
```java
public class Args {
public static void main(String[] args) {
if(test == 1 && test == 1 && test == 1 && test == 1 && test == 1 && test == 1 && test == 1 && test == 1) {
}
}
}
```
output:
```java
public class Args {
public static void main(String[] args) {
if (
test == 1 &&
test == 1 &&
test == 1 &&
test == 1 &&
test == 1 &&
test == 1 &&
test == 1 &&
test == 1
) {}
}
}
```
~~However, it will only breaks on && and ||.
if we have ```if(aVeryVeryVeryVeryVeryVeryVeryVeryVeryLongVariable == aVeryVeryVeryVeryVeryVeryVeryVeryVeryLongVariable2)```, it won't break on ```==```.
Is it bothersome ? I am not sure... It will be hard to tell how we should break each operator since we …
> Fix expression print

- packages/prettier-plugin-java/src/printers/prettier-builder.js
- packages/prettier-plugin-java/test/unit-test/comments/class/_output.java
- packages/prettier-plugin-java/test/unit-test/comments/comments-blocks-and-statements/_output.java
Add a custom line for comments that will always break but will not force parent groups to break.
> fix breaking with multi-lines comments

- packages/java-parser/src/productions/expressions.js
- packages/java-parser/test/bugs-spec.js
Fixing the first issue of #113
> bitshifting operators must no include whitespace

- packages/java-parser/src/comments.js
- packages/prettier-plugin-java/scripts/single-printer-run/_output.java
- packages/prettier-plugin-java/test/unit-test/comments/class/_input.java
- packages/prettier-plugin-java/test/unit-test/comments/class/_output.java
- packages/prettier-plugin-java/test/unit-test/comments/comments-blocks-and-statements/_output.java
- packages/prettier-plugin-java/test/unit-test/comments/interface/_output.java
- packages/prettier-plugin-java/test/unit-test/comments/package/_input.java
- packages/prettier-plugin-java/test/unit-test/comments/package/_output.java
- packages/prettier-plugin-java/test/unit-test/empty_statement/_output.java
- packages/prettier-plugin-java/test/unit-test/expressions/_output.java
This PR modify the comment attachment rule, the issue is we probably have case like #219 and because the way we handle the comment we cannot fix the indent cases or it would be a pain.
So instead of attaching to the closest token it always attach as a leadingComments of the token except when the previous token and the comment is on the same line. This is the most common cases, people (IMO) tend to always put their comments above what they want to comment.
If this attachment rule is problematic, we can easily revert it since this is just a simple piece of the code.
Fix #219
> Attach comments to the next token instead of closest

- packages/java-parser/src/tokens.js
Our project that uses `java-parser` was failed to build.
And we found `java-parser` imports unused `fs` library, which was the cause of the problem.
> Delete 'fs' import because that is not used

- packages/prettier-plugin-java/src/printers/blocks-and-statements.js
- packages/prettier-plugin-java/src/printers/classes.js
- packages/prettier-plugin-java/src/printers/interfaces.js
- packages/prettier-plugin-java/src/printers/prettier-builder.js
- packages/prettier-plugin-java/src/printers/printer-utils.js
- packages/prettier-plugin-java/test/unit-test/comments/package/_output.java
Fixes multi-lines comments as:
```
public class Test<TEST, RZE>
extends Go
implements Alpha, Beta, Alpha, Alpha, Alpha, Alpha, Alpha, Alpha {
/*
comment
*/
@Pointcut("within(@org.springframework.stereotype.Repository *)" +
" || within(@org.springframework.stereotype.Service *)" +
" || within(@org.springframework.web.bind.annotation.RestController *)")
public void springBeanPointcut() {
// Method is empty as this is just a Pointcut, the implementations are in the advices.
}
}
```
The annotation was previously printed on one line. 
It was the last "major" bug I had in mind
> Fix multi-lines comments

- packages/prettier-plugin-java/src/printers/blocks-and-statements.js
- packages/prettier-plugin-java/test/unit-test/variables/_input.java
- packages/prettier-plugin-java/test/unit-test/variables/_output.java
Fix #282 
@lppedd, this would now be formatted like this:
```java
public boolean localVariableDeclarationWhichBreak() {
@Nullable
final BackupStatus lastStatus = BackupStatus.fromDbValue(
backupRepository.getLastStatus()
);
final BackupStatus lastStatus = BackupStatus.fromDbValue(
backupRepository.getLastStatus()
);
@Nullable
BackupStatus lastStatus = BackupStatus.fromDbValue(
backupRepository.getLastStatus()
);
BackupStatus lastStatus = BackupStatus.fromDbValue(
backupRepository.getLastStatus()
);
}
public boolean localVariableDeclarationWhichDoNotBreak() {
@Nullable
final BackupStatus lastStatus = value;
final BackupStatus lastStatus = value;
@Nullable
BackupStatus lastStatus = value;
BackupStatus lastStatus = value;
}
```
> Better display of localVariableDeclarationStatement modifiers

- packages/prettier-plugin-java/src/printers/expressions.js
- packages/prettier-plugin-java/test/unit-test/return/_input.java
- packages/prettier-plugin-java/test/unit-test/return/_output.java
> fix: fix stable reformating when wrapping return statements

- packages/java-parser/.mocharc.js
- packages/java-parser/src/index.js
- packages/java-parser/src/lexer.js
- packages/java-parser/src/parser.js
- packages/java-parser/src/utils.js
Optimize Parser (And Lexer) initialization performance by skipping validation
during productive flows.
The validations are still executed during testing flows using
a mocha configuration file that adds an env variable.
On my Machine the Parser's init time went from 160ms->90ms
And the Lexer's init time went from 30ms->20ms.
Fixes #269
> performance(parser) - Optimize Parser Init

- packages/java-parser/src/productions/packages-and-modules.js
- packages/java-parser/src/tokens.js
- packages/java-parser/test/bugs-spec.js
The Special rule states that: a "transitive" keyword followed by a separator
in the context of a module requires would be parsed as an identifier
which is part of the moduleName instead of as a modifier.
This is handled by:
- Creating Separators token category.
- Adding a GATE before the "module requires" optional modifiers
that inspects the next two tokens.
Fixes #112
> fix(lexer): "transitive" keyword as Identifier in module requires.

- packages/prettier-plugin-java/src/printers/classes.js
- packages/prettier-plugin-java/test/unit-test/args/_input.java
- packages/prettier-plugin-java/test/unit-test/args/_output.java
Fix #303 
Related to #139: I ignored one test case as there is a known bug in the parser we didn't solve yet about variableArityParameters. This test case should be uncommented when this bug is solved.
> fix: fix formating for variable arity parameters with variable modifier

- packages/prettier-plugin-java/docs/modifiers.md
- packages/prettier-plugin-java/src/printers/printer-utils.js
- packages/prettier-plugin-java/test/unit-test/comments/class/_output.java
- packages/prettier-plugin-java/test/unit-test/modifiers/_input.java
- packages/prettier-plugin-java/test/unit-test/modifiers/_output.java
- packages/prettier-plugin-java/test/unit-test/modifiers/modifiers-spec.js
Related to #291 
I had some trouble getting access to the actual modifier name ("public", "static", "private", etc.) and I don't write much javascript so any feedback on the code is welcome. 
There is an existing `sortModifiers` function that everything goes through, however it seems to just separate leading annotations from all other annotations/modifiers. I tried to preserve the behavior of this function, however it conflicts a bit with the new modifier sorting behavior. 
For example, if you have this code:
`final @Annotation private String field;`
Currently, prettier-java leaves this code alone. However, we want to swap the order of the `final` and `private` modifiers, but it's not clear what should happen to `@Annotation` when we do this. As currently written, this PR moves all such …
> Sort modifiers

- packages/prettier-plugin-java/src/printers/expressions.js
- packages/prettier-plugin-java/test/unit-test/binary_expressions/_input.java
- packages/prettier-plugin-java/test/unit-test/binary_expressions/_output.java
- packages/prettier-plugin-java/test/unit-test/comments/class/_output.java
> fix: ternary expression should break before `?` and `:`

- packages/prettier-plugin-java/src/printers/blocks-and-statements.js
- packages/prettier-plugin-java/src/printers/expressions.js
- packages/prettier-plugin-java/test/unit-test/binary_expressions/_input.java
- packages/prettier-plugin-java/test/unit-test/binary_expressions/_output.java
Fixes #306 
I was wondering whether this indentation is desirable for other binary operators, for example `>`, however I think it's better not to start creating heuristics for different binary operators. This also appears to match prettier-js behavior (example below)
Input:
```javascript
function example() {
const greater = someReallyLongExceptionallyUnbelievablyLongIntegerName > anotherReallyLongExceptionallyUnbelievablyLongIntegerName;
const blah = "asldjoewimqwioemwqoiewoiqjeoiamdoimwqioejwqoimdasoidmoqwie" + "qweinaoidnoiqwneoiwqjeoiwqjoiasndoisamdoiqwmeiowqjoieoi" + "qwewhqenwoniosadjoienrmnmziojqoirjqwoeiqowewq";
}
```
Output:
```javascript
function example() {
const greater =
someReallyLongExceptionallyUnbelievablyLongIntegerName > …
```
> Don't indent binary operators

- packages/prettier-plugin-java/src/printers/printer-utils.js
- packages/prettier-plugin-java/test/unit-test/package_and_imports/classWithMixedCaseImports/_input.java
- packages/prettier-plugin-java/test/unit-test/package_and_imports/classWithMixedCaseImports/_output.java
- packages/prettier-plugin-java/test/unit-test/package_and_imports/package_and_imports-spec.js
Fixes #324 
I believe this matches the Google import sort order
https://google.github.io/styleguide/javaguide.html#s3.3.3-import-ordering-and-spacing
> Within each block the imported names appear in ASCII sort order. (Note: this is not the same as the import statements being in ASCII sort order, since '.' sorts before ';'.)
This also appears to better conform to the way IntelliJ/Eclipse sort imports. I looked through the tests for Google's import sorter and tried to cover the same edge cases in the tests I added:
https://github.com/google/google-java-format/blob/master/core/src/test/java/com/google/googlejavaformat/java/ImportOrdererTest.java
> Sort imports naively

- packages/prettier-plugin-java/src/printers/expressions.js
- packages/prettier-plugin-java/test/unit-test/lambda/_input.java
- packages/prettier-plugin-java/test/unit-test/lambda/_output.java
Related to https://github.com/jhipster/prettier-java/issues/311#issuecomment-565098219
Break after arrow when the content is too long and there are no curly braces
cc @andybergon
> Improve formatting of lambda expressions

- packages/prettier-plugin-java/src/printers/classes.js
- packages/prettier-plugin-java/test/unit-test/variables/_input.java
- packages/prettier-plugin-java/test/unit-test/variables/_output.java
Fix #311
Break between equals and method if the content is too long and there are multiple expressions/method calls. It should be consistent with the Prettier style:
```js
const alpha = oaoa().zzazazkzkakzkzkakzkaoaozoaozoaozoaozoazoazooazoazoa() || kzkakzkzkakzkaoaozoaozoaozoaozoazoazooazoazoa()
const alpha = oaoazzaz.ooazoazazkzkakzkzkakzkaoaozoaozaaaaaaaopdahpdjpajaoaozoaozoazoazooazoazoa()
```
is transformed in:
```js
const alpha =
oaoa().zzazazkzkakzkzkakzkaoaozoaozoaozoaozoazoazooazoazoa() ||
kzkakzkzkakzkaoaozoaozoaozoaozoazoazooazoazoa();
const alpha = oaoazzaz.ooazoazazkzkakzkzkakzkaoaozoaozaaaaaaaopdahpdjpajaoaozoaozoazoazooazoazoa();
```
> Improve formatting of variable initialization

- packages/prettier-plugin-java/src/printers/blocks-and-statements.js
- packages/prettier-plugin-java/src/printers/comments.js
- packages/prettier-plugin-java/src/printers/packages-and-modules.js
- packages/prettier-plugin-java/src/printers/printer-utils.js
- packages/prettier-plugin-java/test/unit-test/blank_lines/_output.java
- packages/prettier-plugin-java/test/unit-test/comments/class/_output.java
- packages/prettier-plugin-java/test/unit-test/formatter-on-off/inside_block/_output.java
> Better respect of blank lines with comments

- packages/prettier-plugin-java/src/printers/classes.js
- packages/prettier-plugin-java/test/unit-test/enum/_output.java
Fix #309
In this PR, I always add a blank line before enumBodyDeclarations.
So we would get this formatting
```java
// This input
public enum EnumWithExtraCommaAndEnumBodyDeclarations {
THIS_IS_GOOD("abc"),
THIS_IS_FINE("abc");
public static final String thisWillBeDeleted = "DELETED";
}
// or this input
public enum EnumWithExtraCommaAndEnumBodyDeclarations {
THIS_IS_GOOD("abc"),
THIS_IS_FINE("abc");
public static final String thisWillBeDeleted = "DELETED";
}
// will be formatted to this output
public enum EnumWithExtraCommaAndEnumBodyDeclarations {
THIS_IS_GOOD("abc"),
THIS_IS_FINE("abc");
public static final String thisWillBeDeleted = "DELETED";
}
```
> feature: add blank line in enums between constants & declarations

- packages/prettier-plugin-java/src/printers/classes.js
- packages/prettier-plugin-java/test/unit-test/enum/_input.java
- packages/prettier-plugin-java/test/unit-test/enum/_output.java
Fix #259 
- blank lines are not completely removed in enumConstant lists: we allow one blank line between two enum constants
```java
// Input
public enum OtherEnum {
ONE, TWO,
THREE,
FOUR,
/* Five */
FIVE,
/* Six */
SIX
}
// Output
public enum OtherEnum {
ONE, 
TWO,
THREE,
FOUR,
/* Five */
FIVE,
/* Six */
SIX
}
```
> feature: allow blank lines in enumConstant lists

- packages/prettier-plugin-java/src/printers/expressions.js
- packages/prettier-plugin-java/src/printers/printer-utils.js
- packages/prettier-plugin-java/test/unit-test/binary_expressions/_input.java
- packages/prettier-plugin-java/test/unit-test/binary_expressions/_output.java
Move comments before binaryOperator to the following unaryExpression
Fix #352
By comparison, what is done in Prettier for TS:
```sh
--parser typescript
```
**Input:**
```tsx
a = one || two >> 1 // one
// two
// three
|| //four
// five
three;
```
**Output:**
```tsx
a =
one ||
two >> 1 || // one //four
// two
// three
// five
three;
```
> fix: move comments in binaryExpression

- packages/prettier-plugin-java/src/cst-printer.js
- packages/prettier-plugin-java/src/printer.js
- packages/prettier-plugin-java/src/printers/arrays.js
- packages/prettier-plugin-java/src/printers/classes.js
- packages/prettier-plugin-java/src/printers/interfaces.js
- packages/prettier-plugin-java/src/printers/prettier-builder.js
- packages/prettier-plugin-java/src/printers/printer-utils.js
- packages/prettier-plugin-java/test/test-utils.js
- packages/prettier-plugin-java/test/unit-test/snippets/arrays/array-initializer.spec.js
- packages/prettier-plugin-java/test/unit-test/snippets/arrays/variable-initializer-list.spec.js
- packages/prettier-plugin-java/test/unit-test/snippets/classes/enum-body.spec.js
- packages/prettier-plugin-java/test/unit-test/snippets/classes/variableDeclarator/test.spec.js
- packages/prettier-plugin-java/test/unit-test/snippets/interfaces/element-value-array-initializer.spec.js
- packages/prettier-plugin-java/test/unit-test/snippets/names/ambiguousName/test.spec.js
- packages/prettier-plugin-java/test/unit-test/snippets/names/expressionName/test.spec.js
- packages/prettier-plugin-java/test/unit-test/snippets/names/methodName/test.spec.js
- packages/prettier-plugin-java/test/unit-test/snippets/names/packageOrTypeName/test.spec.js
- packages/prettier-plugin-java/test/unit-test/snippets/types-values-and-variables/floatingPointType/test.spec.js
- packages/prettier-plugin-java/test/unit-test/snippets/types-values-and-variables/integralType/test.spec.js
- packages/prettier-plugin-java/test/unit-test/snippets/types-values-and-variables/numericType/test.spec.js
- packages/prettier-plugin-java/test/unit-test/snippets/types-values-and-variables/wildcard/test.spec.js
- packages/prettier-plugin-java/test/unit-test/snippets/types-values-and-variables/wildcardBounds/test.spec.js
- Add options support for trailing commas in enum and arrays
**options:**
```sh
--trailing-comma all
```
```java
// Input
public enum Enum {
ONE, TWO, THREE
}
// Output
public enum Enum {
ONE, 
TWO,
THREE,
}
```
```java
// Input
public class T {
void t() {
int[] ints = { 1, 2, 3, };
int[] ints = { aVeryLongArrayValue, anotherVeryLongArrayValue, andYetAnotherVeryLongArrayValue };
}
}
// Output
public class T {
void t() {
int[] ints = { 1, 2, 3 };
int[] ints = {
aVeryLongArrayValue,
anotherVeryLongArrayValue,
andYetAnotherVeryLongArrayValue,
};
}
}
```
**Relative issues or prs:**
Relative to #313, #314 and #319 
cc @natdempk and @jhaber
> Add option support for trailing comma in enums

- packages/prettier-plugin-java/src/printers/blocks-and-statements.js
- packages/prettier-plugin-java/test/unit-test/snippets/blocks-and-statements/switch.spec.js
- packages/prettier-plugin-java/test/unit-test/switch/_input.java
- packages/prettier-plugin-java/test/unit-test/switch/_output.java
Fix line wrapping of switch statements: do not try to print the switch statement in one line
```java
// Input
public String shouldWrapEvenForSmallSwitchCases() {
switch (answer) { case "YES": return "YES"; default: return "NO"; }
}
// Output (v0.6.0)
public String shouldWrapEvenForSmallSwitchCases() {
switch (answer) { case "YES": return "YES"; default: return "NO"; }
}
// Output after PR:
public String shouldWrapEvenForSmallSwitchCases() {
switch (answer) {
case "YES":
return "YES";
default:
return "NO";
}
}
```
Fix #357
> fix: line wrapping in switch statements

- packages/prettier-plugin-java/src/printers/printer-utils.js
- packages/prettier-plugin-java/test/unit-test/empty_statement/_input.java
- packages/prettier-plugin-java/test/unit-test/empty_statement/_output.java
- packages/prettier-plugin-java/test/unit-test/snippets/classes/class-body.spec.js
Fix line breaks in class bodies with empty statements. The calculation of separators between class member declarations was not taking account correctly of empty statements.
```java
// Input
public class Test {
public TestField testField;;
@Override
public void someMethod() {}
}
// Output (v0.6.0)
public class Test {
public TestField testField;
@Override
public void someMethod() {}
}
// Output after PR:
public class Test {
public TestField testField;
@Override
public void someMethod() {}
}
```
Fix #356
> fix: blank lines with empty statements

- packages/prettier-plugin-java/src/printers/printer-utils.js
- packages/prettier-plugin-java/test/unit-test/blank_lines/_input.java
- packages/prettier-plugin-java/test/unit-test/blank_lines/_output.java
Fix stable formatting of fields & methods with annotations: if an annotation was added before other modifiers, the input needed to be formatted twice
```java
// Input
class T {
private String fieldOne;
private String fieldTwo;
private @Nullable String shouldAddLineBeforeAndAfter;
private String fieldThree;
private String fieldFour;
}
// Output
class T {
private String fieldOne;
private String fieldTwo;
@Nullable
private String shouldAddLineBeforeAndAfter;
private String fieldThree;
private String fieldFour;
}
```
Fix #368
> fix: fix stable formatting for fields & methods with annotations

- packages/prettier-plugin-java/src/printers/classes.js
- packages/prettier-plugin-java/test/unit-test/enum/_input.java
- packages/prettier-plugin-java/test/unit-test/enum/_output.java
Fix handling of empty enums to not insert a trailing comma
The tests show examples of the new behavior. Without this PR, the output is:
```java
public enum EmptyEnum {
,
}
public enum EmptyEnumWithComment {
,
// comment
}
```
Which doesn't compile
> fix: empty enums

- packages/prettier-plugin-java/src/printers/classes.js
- packages/prettier-plugin-java/test/unit-test/enum/_input.java
- packages/prettier-plugin-java/test/unit-test/enum/_output.java
```java
// Input
enum PrettierErrors {
WE_LOVE_PRETTIER,
// And I can't believe
// it is free
// why are people
// so damn generous
;
void printTest() {
System.out.println("Hey there");
}
}
// Output
enum PrettierErrors {
WE_LOVE_PRETTIER
// And I can't believe
// it is free
// why are people
// so damn generous
;
void printTest() {
System.out.println("Hey there");
}
}
```
Fix #383
> fix: comment on enum

- package.json
- packages/prettier-plugin-java/package.json
- yarn.lock
Updates:
- Prettier to 2.0.4
- ESLint to 6.8.0
- eslint-config-google to 0.14.0
- eslint-config-prettier to 6.10.1
- husky to 4.2.5
- lerna to 3.20.2
- lint-staged to 10.1.4
- mocha to 7.1.1
- nyc to 15.0.1
- sinon to 9.0.2
> chore: update libs

- .github/workflows/binaries.yml
- .github/workflows/github-ci.yml
This PR will provide binary artifacts on github release.
Working on linux but I have tested for macos or windows thought.
Close #326
```java
// Input
// Output
```
> feat: upload binary artifacts on github release

- .huskyrc.js
```java
// Input
// Output
```
> fix: unknown sed option on macos

- packages/prettier-plugin-java/src/printers/expressions.js
- packages/prettier-plugin-java/test/unit-test/indent/_input.java
- packages/prettier-plugin-java/test/unit-test/indent/_output.java
- packages/prettier-plugin-java/test/unit-test/indent/indent-spec.js
Fix #293
```java
// Input
class Indent {
void indetMethod() {
assertThat(
useraaaaaaaaaaojzapjzpozjapjzpoajzpozaaaaaaaaaaaMapperlaaaaaaaaaaaaaaaaaaaaaaaa,
useraaaaaaaaaaojzapjzpozjapjzpoajzpozaaaaaaaaaaaMapperlaaaaaaaaaaaaaaaaaaaaaaaa,
useraaaaaaaaaaojzapjzpozjapjzpoajzpozaaaaaaaaaaaMapperlaaaaaaaaaaaaaaaaaaaaaaaa
);
assertThat(
useraaaaaaaaaaojzapjzpozjapjzpoajzpozaaaaaaaaaaaMapperlaaaaaaaaaaaaaaaaaaaaaaaa,
useraaaaaaaaaaojzapjzpozjapjzpoajzpozaaaaaaaaaaaMapperlaaaaaaaaaaaaaaaaaaaaaaaa,
useraaaaaaaaaaojzapjzpozjapjzpoajzpozaaaaaaaaaaaMapperlaaaaaaaaaaaaaaaaaaaaaaaa
)
.isEqualTo();
assertThat(
useraaaaaaaaaaojzapjzpozjapjzpoajzpozaaaaaaaaaaaMapperlaaaaaaaaaaaaaaaaaaaaaaaa,
useraaaaaaaaaaojzapjzpozjapjzpoajzpozaaaaaaaaaaaMapperlaaaaaaaaaaaaaaaaaaaaaaaa, …
```
> fix: Wrong indent in some methods invocation

- packages/prettier-plugin-java/src/printers/expressions.js
- packages/prettier-plugin-java/test/unit-test/instantiation/_input.java
- packages/prettier-plugin-java/test/unit-test/instantiation/_output.java
Fix #381 
```java
// Input
public class MethodWrappingFollowingContstructor {
public static void callMethod() {
new MethodWrappingFollowingContstructor().aLongEnoughMethodNameToForceThingsToWrap();
System.out.println(
"This operation with two very long string should break" +
"in a very nice way"
);
}
public void aLongEnoughMethodNameToForceThingsToWrap() {}
}
// Output
public class MethodWrappingFollowingContstructor {
public static void callMethod() {
new MethodWrappingFollowingContstructor()
.aLongEnoughMethodNameToForceThingsToWrap();
System.out.println(
"This operation with two very long string should break" +
"in a very nice way"
);
}
public void aLongEnoughMethodNameToForceThingsToWrap() {}
}
```
> fix: wrong indent on single method call following a constructor 

- packages/prettier-plugin-java/src/printers/expressions.js
- packages/prettier-plugin-java/test/unit-test/expressions/_input.java
- packages/prettier-plugin-java/test/unit-test/expressions/_output.java
Fix #339
```java
// Input
public void longFullyQualifiedName() {
com.me.very.very.very.very.very.very.very.very.very.very.very.very.very.longg.fully.qualified.name.FullyQualifiedName.builder().build();
com.FullyQualifiedName.builder();
}
// Output
public void longFullyQualifiedName() {
com.me.very.very.very.very.very.very.very.very.very.very.very.very.very.longg.fully.qualified.name.FullyQualifiedName
.builder()
.build();
com.FullyQualifiedName.builder();
}
```
> fix: Long fully qualified name indent

- README.md
Improving the README documentation so that it shows what part of the pom.xml the plugin entry belongs in. It's been a while since I've used Maven, so it took me a little while to figure out how to actually use this plugin in a fresh pom.xml without a <plugins> block.
> Add more context to the Maven plugin usage

- CHANGELOG.md
- package.json
- packages/java-parser/api.d.ts
- packages/java-parser/src/productions/classes.js
- packages/java-parser/src/productions/expressions.js
- packages/java-parser/test/bugs-spec.js
- packages/prettier-plugin-java/package.json
- packages/prettier-plugin-java/src/options.js
- packages/prettier-plugin-java/src/printers/classes.js
- packages/prettier-plugin-java/src/printers/expressions.js
- packages/prettier-plugin-java/test/unit-test/expressions/_input.java
- packages/prettier-plugin-java/test/unit-test/expressions/_output.java
Fix the BC caused by fixing the unannPrimitive parsing. #412 & #421 
Fix transitive dependencies isses between prettier-plugin-java & java-parser
> Fix transitive dependencies

- packages/prettier-plugin-java/scripts/single-printer-run/_output.java
- packages/prettier-plugin-java/src/printers/classes.js
- packages/prettier-plugin-java/test/unit-test/blank_lines/_output.java
- packages/prettier-plugin-java/test/unit-test/char_literal/_output.java
- packages/prettier-plugin-java/test/unit-test/classes/_output.java
- packages/prettier-plugin-java/test/unit-test/comments/class/_output.java
- packages/prettier-plugin-java/test/unit-test/comments/comments-blocks-and-statements/complex/_output.java
- packages/prettier-plugin-java/test/unit-test/comments/comments-blocks-and-statements/end-of-block/_output.java
- packages/prettier-plugin-java/test/unit-test/complex_generic_class/_output.java
- packages/prettier-plugin-java/test/unit-test/empty_statement/_output.java
- packages/prettier-plugin-java/test/unit-test/generic_class/_output.java
- packages/prettier-plugin-java/test/unit-test/marker_annotations/_output.java
- packages/prettier-plugin-java/test/unit-test/modifiers/_output.java
- packages/prettier-plugin-java/test/unit-test/prettier-ignore/method/_output.java
- packages/prettier-plugin-java/test/unit-test/prettier-ignore/multiple-ignore/_output.java
- packages/prettier-plugin-java/test/unit-test/snippets/classes/class-body.spec.js
- packages/prettier-plugin-java/test/unit-test/variables/_output.java
Fix #271
```java
// Input
public class JWTFilter extends GenericFilterBean {
public static final String AUTHORIZATION_HEADER = "Authorization";
private TokenProvider tokenProvider;
}
// Output
public class JWTFilter extends GenericFilterBean {
public static final String AUTHORIZATION_HEADER = "Authorization";
private TokenProvider tokenProvider;
}
```
However it should be noted that we can have this case:
```java
// Input
public class MyClass {
public void myMethod() {
return new AnonymousClass() {
int a;
}
}
}
// Output
public class MyClass {
public void myMethod() {
return new AnonymousClass() {
int a;
}
}
}
```
Since inside the class this is also a classBodyDeclaration node.
I think we can probably make an exception on class body for anonymous class but I don't know if we should.
> fix: enforce blank line after body declaration

- packages/prettier-plugin-java/src/printers/classes.js
- packages/prettier-plugin-java/test/unit-test/comments/interface/_output.java
- packages/prettier-plugin-java/test/unit-test/throws/_input.java
- packages/prettier-plugin-java/test/unit-test/throws/_output.java
This is a modified version of #305 that makes a more minor change. Based on #286 it seems like there's not a clear answer on how formatting should work when methods throw lots of exceptions. However, the current behavior where there's an extra newline is basically a bug, for example:
```java
public void method(
Arg arg1,
Arg arg2
)
throws Exception {}
```
This PR attempts to fix the bug, while punting on the question of a more complete behavior change.
The tests should give a good idea of the behavior I was going for. Unfortunately, my prettier fu is pretty weak so a few of the tests are failing and I'm having a hard time getting things just right
> fix: throws rendering

- packages/java-parser/api.d.ts
- packages/java-parser/src/productions/classes.js
- packages/java-parser/src/productions/expressions.js
- packages/java-parser/test/bugs-spec.js
- packages/prettier-plugin-java/src/options.js
- packages/prettier-plugin-java/src/printers/classes.js
- packages/prettier-plugin-java/src/printers/expressions.js
- packages/prettier-plugin-java/test/unit-test/expressions/_input.java
- packages/prettier-plugin-java/test/unit-test/expressions/_output.java
Put back the fix for parsing unannPrimitiveType with dims
#412, #421 & #425
> Revert "Revert "fix: fix parsing of unannPrimitiveType in primary""

- packages/prettier-plugin-java/src/printers/blocks-and-statements.js
- packages/prettier-plugin-java/test/unit-test/switch/_input.java
- packages/prettier-plugin-java/test/unit-test/switch/_output.java
- packages/prettier-plugin-java/test/unit-test/yield-statement/_output.java
Fix #439
```java
// Input
public void multipleCaseConstants(TestEnum testEnum) {
switch (testEnum) {
case FOO -> System.out.println("Foo!");
case BAR, BAZ -> System.out.println("Not Foo!");
case BAR, BAZ, BAZ, BAZ, BAZ, BAZ, BAZ, BAZ, BAZ, BAZ, BAZ, BAZ, BAZ, BAZ, BAZ, BAZ, BAZ, BAZ, BAZ, BAZ -> System.out.println("Not Foo!");
}
}
public void caseConstantsWithComments(TestEnum testEnum) {
switch (testEnum) {
case BAR /* foo */, BAZ -> System.out.println("Not Foo!");
case BAR /* foo */, /* bar */ BAZ -> System.out.println("Not Foo!");
case BAR, /* bar */ BAZ -> System.out.println("Not Foo!");
}
}
// Output
public void multipleCaseConstants(TestEnum testEnum) {
switch (testEnum) {
case FOO -> System.out.println("Foo!");
case BAR, BAZ -> System.out.println("Not Foo!");
case BAR,
BAZ,
BAZ, …
```
> fix: space before comma in multi-value switch expression case label

- packages/prettier-plugin-java/src/printers/expressions.js
- packages/prettier-plugin-java/test/unit-test/comments/bug-fixes/_input.java
- packages/prettier-plugin-java/test/unit-test/comments/bug-fixes/_output.java
```java
// Input
public static final List<Object> XXXXXXXXXXXXXXXXXX = Collections.unmodifiableList(
Arrays.asList(// a
// b
// c
// d
)
);
public static final List<Object> XXXXXXXXXXXXXXXXXX = Collections.unmodifiableList(
Arrays.asList(// a
// b
// c
// d
/*e*/)
);
// Before PR
public static final List<Object> XXXXXXXXXXXXXXXXXX = Collections.unmodifiableList(
Arrays.asList(// b // a
// c
// d
)
);
// After PR
public static final List<Object> XXXXXXXXXXXXXXXXXX = Collections.unmodifiableList(
Arrays.asList( // a
// b
// c
// d
)
);
public static final List<Object> XXXXXXXXXXXXXXXXXX = Collections.unmodifiableList(
Arrays.asList( // a
// b
// c
// d
/*e*/
)
);
```
Fix #443
> fix: stable reformating for method invocation with only comments

- packages/java-parser/README.md
Fixed broken Chevrotain links in the `java-parser` readme.
> Fix Chevrotain links in java-parser readme

- packages/java-parser/src/productions/expressions.js
- packages/java-parser/test/blocks-and-statements/switch-case-spec.js
- packages/java-parser/test/blocks-and-statements/yield-statement-spec.js
- packages/java-parser/test/pattern-matching/pattern-matching-spec.js
- packages/java-parser/test/records/records-spec.js
- packages/prettier-plugin-java/src/options.js
- packages/prettier-plugin-java/src/printers/expressions.js
- packages/prettier-plugin-java/src/printers/printer-utils.js
- packages/prettier-plugin-java/test/unit-test/pattern-matching/_input.java
- packages/prettier-plugin-java/test/unit-test/pattern-matching/_output.java
- packages/prettier-plugin-java/test/unit-test/pattern-matching/pattern-matching-spec.js
Support instance of pattern matching: https://docs.oracle.com/javase/specs/jls/se16/html/jls-15.html#jls-InstanceofExpression
```java
// Input
class T {
static String formatter(Object o) {
String formatted = "unknown";
if (o instanceof Integer i || p instanceof Point || q instanceof Circle c || r instanceof Square) {
formatted = String.format("int %d", i);
} else if (o instanceof Long l) {
formatted = String.format("long %d", l);
} else if (o instanceof Double d) {
formatted = String.format("double %f", d);
} else if (o instanceof String s) {
formatted = String.format("String %s", s);
}
return formatted;
}
}
// Output
class T {
static String formatter(Object o) {
String formatted = "unknown";
if (
o instanceof Integer i ||
p instanceof Point ||
q instanceof Circle c ||
r instanceof Square …
```
> feat: support instance of pattern matching

- packages/prettier-plugin-java/src/printers/classes.js
- packages/prettier-plugin-java/test/unit-test/constructors/_input.java
- packages/prettier-plugin-java/test/unit-test/constructors/_output.java
```java
// Input
public <T> GenericConstructor(T genericParameter) {}
// Prettier 1.2.0
public <T>GenericConstructor(T genericParameter) {}
// Updated version
public <T> GenericConstructor(T genericParameter) {}
```
Fix #484
> feat: add space after type parameter in generic constructor

- packages/java-parser/src/productions/interfaces.js
- packages/java-parser/test/records/records-spec.js
- packages/prettier-plugin-java/test/unit-test/records/_input.java
- packages/prettier-plugin-java/test/unit-test/records/_output.java
This PR is intended to fix an error when parsing interfaces with inner records.
```java
// Input
public interface SomeInterface {
record SomeRecord(
String param
) implements AnyInterface { }
}
// Output
AssertionError: expected [Function] to not throw an error but 
Error: Sad sad panda, parsing errors detected in line: 5, column: 9!
Expecting: one of these possible Token sequences:\n  1. [\'{\'] 2. [\';\']
but found: \'implements\'!
->compilationUnit
->ordinaryCompilationUnit
->typeDeclaration
->interfaceDeclaration
->normalInterfaceDeclaration
->interfaceBody
->interfaceMemberDeclaration
->interfaceMethodDeclaration
->methodBody' was thrown
```
As I understand it, `interfaceMemberDeclaration->interfaceMethodDeclaration` is a sign that the inner record is being identified as a method …
> Fix interface member detection to support inner records

- packages/prettier-plugin-java/src/printers/classes.ts
- packages/prettier-plugin-java/src/printers/expressions.ts
- packages/prettier-plugin-java/src/utils/expressions-utils.ts
- packages/prettier-plugin-java/src/utils/index.ts
- packages/prettier-plugin-java/src/utils/printArgumentListWithBraces.ts
- packages/prettier-plugin-java/src/utils/printSingleLambdaInvocation.ts
- packages/prettier-plugin-java/test/unit-test/lambda/_input.java
- packages/prettier-plugin-java/test/unit-test/lambda/_output.java
Still needs to clean the Typescript migration PR before but hopefully should close #418
```java
// Input
public class Lambda {
public void singleArgumentWithParens() {
call((x) -> {
System.out.println(x);
System.out.println(x);
});
}
public void singleArgumentWithoutParens() {
call(x -> {
System.out.println(x);
System.out.println(x);
});
}
public void multiArguments() {
call((x, y) -> {
System.out.println(x);
System.out.println(y);
});
}
public void multiParameters() {
call((Object x, final String y) -> {
System.out.println(x);
System.out.println(y);
});
}
public void emptyArguments() {
call(() -> {
System.out.println();
System.out.println();
});
}
public void onlyOneMethodInBodyWithCurlyBraces() {
call(x -> {
System.out.println(x);
});
}
public void onlyOneMethodInBody() {
call(x -> …
```
> Fix: lambda formatting

- packages/java-parser/src/productions/blocks-and-statements.js
- packages/java-parser/test/bugs-spec.js
- packages/prettier-plugin-java/test/unit-test/yield-statement/_input.java
- packages/prettier-plugin-java/test/unit-test/yield-statement/_output.java
```java
// Input
void should_not_throw_on_yield_static_imports() {
Thread.yield ();
yield();
yield(a);
}
// Output
void should_not_throw_on_yield_static_imports() {
Thread.yield();
yield();
yield (a);
}
```
Fix #498
> fix: do not crash on yield static imports

- packages/java-parser/api.d.ts
- packages/java-parser/src/productions/expressions.js
- packages/prettier-plugin-java/src/printers/expressions.ts
- packages/prettier-plugin-java/test/unit-test/expressions/_input.java
- packages/prettier-plugin-java/test/unit-test/expressions/_output.java
Remove useless inline rules in Java parser, that makes more complex visitor without adding much value
No changes in the printer.
None
> refactor: remove nested inline rules in java parser

- packages/prettier-plugin-java/src/printers/classes.ts
- packages/prettier-plugin-java/test/unit-test/records/_input.java
- packages/prettier-plugin-java/test/unit-test/records/_output.java
Split record parameters on several lines if does not fit on one line
```java
// Input
public record Person(
String firstName, String lastName, String email,
String phoneNumber,
String streetAddress,
String city,
String state,
String zipCode
) {}
// Output before this PR
public record Person(
String firstName, String lastName, String email, String phoneNumber, String streetAddress, String city, String state, String zipCode
) {}
// Output with this PR
public record Person(
String firstName,
String lastName,
String email,
String phoneNumber,
String streetAddress,
String city,
String state,
String zipCode
) {}
```
Fix #507
> feat: split record parameters on several lines

- packages/prettier-plugin-java/src/printers/expressions.ts
- packages/prettier-plugin-java/test/unit-test/cast/_input.java
- packages/prettier-plugin-java/test/unit-test/cast/_output.java
- packages/prettier-plugin-java/test/unit-test/cast/cast-spec.ts
```java
// Input
void should_cast_with_single_element() {
var myElem = (int) othrElement;
var myElem = (A) othrElement;
var myElem = (A) (othrElement, value) -> othrElement + value;
var myElem = (Aaeaozeaonzeoazneaozenazonelkadndpndpazdpazdpazdpazdpazeazpeaazdpazdpazpdazdpa) othrElement;
}
void should_cast_with_additional_bounds() {
foo((A & B) obj);
foo((A & B & C) obj);
foo((Aaeaozeaonzeoazneaozenazone & Bazoieoainzeonaozenoazne & Cjneazeanezoanezoanzeoaneonazeono) obj);
foo((Aaeaozeaonzeoazneaozenazone & Bazoieoainzeonaozenoazne & Cjneazeanezoanezoanzeoaneonazeono) (othrElement, value) -> othrElement + value);
}
// Output before PR
void should_cast_with_single_element() {
var myElem = (int) othrElement;
var myElem = (A) othrElement;
var myElem = (A) (othrElement, value) -> othrElement …
```
> fix: fix casting with additional bounds

- packages/prettier-plugin-java/src/printers/classes.ts
- packages/prettier-plugin-java/src/printers/printer-utils.ts
- packages/prettier-plugin-java/test/unit-test/records/_input.java
- packages/prettier-plugin-java/test/unit-test/records/_output.java
```java
// Input
public record Record(
@JsonSerialize(using = StatusSerializer.class, nullsUsing = NullSerializer.class)
@Schema(type = "integer", description = "Some fancy description")
Status status,
@NotNull
Integer number
) {}
public record Record(
@JsonSerialize(using = StatusSerializer.class, nullsUsing = NullSerializer.class)
@Schema(type = "integer", description = "Some fancy description")
// comment
Status status,
// another comment
@NotNull
Integer number
) {}
// Before PR
public record Record(
@JsonSerialize(
using = StatusSerializer.class,
nullsUsing = NullSerializer.class
) @Schema(
type = "integer",
description = "Some fancy description"
) Status status,
@NotNull Integer number
) {}
public record Record(
@JsonSerialize(
using = StatusSerializer.class,
nullsUsing = …
```
> feat: improve records arguments printing

- packages/java-parser/src/productions/classes.js
- packages/java-parser/test/sealed/sealed-spec.js
- packages/prettier-plugin-java/test/unit-test/sealed/_input.java
- packages/prettier-plugin-java/test/unit-test/sealed/_output.java
Fix parsing of nested sealed and non-sealed classes
```java
// Input
package nl.jqno.equalsverifier.integration.extended_contract;
public class SealedClasses {
public static sealed abstract class SealedParent permits SealedChild {}
final static class SealedChild extends SealedParent {}
}
// Output
public class NestedSealedClasses {
public abstract static sealed class SealedParent permits SealedChild {}
static final class SealedChild extends SealedParent {}
}
```
Fix #522
> fix: correct parsing of nested sealed classes

- .github/workflows/github-ci.yml
- LICENSE
- NOTICE
- related to https://github.com/jhipster/generator-jhipster/issues/17509
> Update License to 2022

- packages/java-parser/src/productions/interfaces.js
- packages/java-parser/test/sealed/sealed-spec.js
- packages/prettier-plugin-java/test/unit-test/sealed/_input.java
- packages/prettier-plugin-java/test/unit-test/sealed/_output.java
Fix parsing of sealed/non-sealed classes & interfaces in an interface's body
**Example**
```java
public interface Test {
sealed interface Inner {}
public static sealed abstract class SealedParent {}
non-sealed interface Inner {}
public static non-sealed abstract class SealedParent {}
final static class SealedChild extends SealedParent {}
}
```
Fix #533
> fix: fix parsing of nested sealed interfaces and classes

- packages/prettier-plugin-java/src/printers/types-values-and-variables.ts
- packages/prettier-plugin-java/test/unit-test/generic_class/_input.java
- packages/prettier-plugin-java/test/unit-test/generic_class/_output.java
```java
// Input
public class Foo<T> {
public <U extends @NotNull T> void example(U u) {}
public <U extends com.java.Any.@NotNull T> void example(U u) {}
}
// Prettier 1.6.1
public class Foo<T> {
public <U extends @NotNullT> void example(U u) {}
public <U extends com.java.Any.@NotNullT> void example(U u) {}
}
// Next
public class Foo<T> {
public <U extends @NotNull T> void example(U u) {}
public <U extends com.java.Any.@NotNull T> void example(U u) {}
}
```
Fix #536
> fix: add space after annotation in typeBounds

- packages/java-parser/src/tokens.js
- packages/java-parser/test/string-literals.spec.js
Fix parsing of escaped spaces in strings like these following example
```java
"\s"
```
Fix #541
> fix: fix parsing of escaped spaces in strings

- README.md
Add configuration for import order in VSCode to the README.md
> doc: add VSCode Java import order configuration

- packages/prettier-plugin-java/src/index.js
- packages/prettier-plugin-java/test/test-utils.ts
- packages/prettier-plugin-java/test/unit-test/require-pragma/format-pragma/_input.java
- packages/prettier-plugin-java/test/unit-test/require-pragma/format-pragma/_output.java
- packages/prettier-plugin-java/test/unit-test/require-pragma/invalid-pragma/_input.java
- packages/prettier-plugin-java/test/unit-test/require-pragma/invalid-pragma/_output.java
- packages/prettier-plugin-java/test/unit-test/require-pragma/prettier-pragma/_input.java
- packages/prettier-plugin-java/test/unit-test/require-pragma/prettier-pragma/_output.java
- packages/prettier-plugin-java/test/unit-test/require-pragma/require-pragma-spec.ts
Added support for the require-pragma option
```java
// Input
/**
* @prettier
*/
public class Example { private int test=-1;}
// Output
/**
* @prettier
*/
public class Example {
private int test = -1;
}
```
```java
// Input
public class Example { private int test=-1;}
// Output
public class Example { private int test=-1;}
```
https://github.com/jhipster/prettier-java/issues/573
> Added support for require-pragma option (resolves #573)

- packages/prettier-plugin-java/src/printers/classes.ts
- packages/prettier-plugin-java/src/printers/prettier-builder.ts
- packages/prettier-plugin-java/test/unit-test/cast/_output.java
- packages/prettier-plugin-java/test/unit-test/comments/bug-fixes/_output.java
- packages/prettier-plugin-java/test/unit-test/variables/_input.java
- packages/prettier-plugin-java/test/unit-test/variables/_output.java
Long assignments (i.e. those that previously violated printWidth) of many types now break after equals the way Prettier JavaScript now does.
```java
Object aParticularlyLongAndObnoxiousNameForIllustrativePurposes = new Object()
.someMethod();
Object[] aParticularlyLongAndObnoxiousNameForIllustrativePurposes2 = new Object[] {
new Object(),
new Object()
};
Object aParticularlyLongAndObnoxiousNameForIllustrativePurposes3 = SomeClass.someStaticMethod();
Object aParticularlyLongAndObnoxiousNameForIllustrativePurposes = someMethod()
.anotherMethod();
Object aParticularlyLongAndObnoxiousNameForIllustrativePurposes = anotherValue !=
null
? anotherValue
: new Object();
}
}
```
```java
Object …
```
> fix: break long assignments after equals

- packages/prettier-plugin-java/scripts/clone-samples.js
All of the JHipster repositories that this project uses as samples for its E2E tests had their main branches updated last week with 2 breaking changes:
1. They now require Java 17 to build.
2. Their `mvnw` script is no longer executable (@pascalgrimaud apologies for the notification, but I thought JHipster might want to be made aware of this issue, as I assume this was changed by mistake).
Both of these changes broke this repository's CI checks. The first change would be easy enough for us to resolve, we can simply upgrade the version of Java in `github-ci.yml`. However, the second change is not as easy for us to fix, nor should we have to fix it here, so we'll likely need to wait until those other repositories are updated to re-set the executable bit on their `mvnw` script.
To work …
> ci: downgrade E2E JHipster samples

- packages/prettier-plugin-java/src/printers/types-values-and-variables.ts
- packages/prettier-plugin-java/test/unit-test/variables/_input.java
- packages/prettier-plugin-java/test/unit-test/variables/_output.java
Long lines containing type arguments (i.e. those that previously violated printWidth) are now broken on type arguments the way Prettier JavaScript does (on TypeScript).
```java
<A extends ShortClassName & ShortClassName & ShortClassName & ShortClassName, B extends ShortClassName & ShortClassName & ShortClassName & ShortClassName & ShortClassName, C extends ExtremelyLongAndObnoxiousClassName<ExtremelyLongAndObnoxiousClassName<ExtremelyLongAndObnoxiousClassName, ExtremelyLongAndObnoxiousClassName>, ExtremelyLongAndObnoxiousClassName> & ExtremelyLongAndObnoxiousInterfaceName & ExtremelyLongAndObnoxiousInterfaceName & ExtremelyLongAndObnoxiousInterfaceName> void example(
ExtremelyLongAndObnoxiousClassName<ExtremelyLongAndObnoxiousClassName> parameter, …
```
> feat: break long lines on type arguments

- packages/prettier-plugin-java/src/printers/classes.ts
- packages/prettier-plugin-java/test/unit-test/binary_expressions/_input.java
- packages/prettier-plugin-java/test/unit-test/binary_expressions/_output.java
Assignments containing a binary expression beginning with a cast now break and indent the way Prettier JavaScript does.
```java
public class Test {
public static void main(String[] args) {
if (oneLevelDeep) {
if (twoLevelsDeep) {
if (threeLevelsDeep) {
int successfulCount = 0;
int failureCount = 1;
double availability = (double) successfulCount / (successfulCount + failureCount);
}
}
}
}
}
```
```java
public class Test {
public static void main(String[] args) {
if (oneLevelDeep) {
if (twoLevelsDeep) {
if (threeLevelsDeep) {
int successfulCount = 0;
int failureCount = 1;
double availability =
(double) successfulCount / (successfulCount + failureCount);
}
}
}
}
}
```
Fix #396
> fix(printer): break and indent binary expression with cast properly

- packages/prettier-plugin-java/src/printers/lexical-structure.ts
- packages/prettier-plugin-java/test/unit-test/text-blocks/_input.java
- packages/prettier-plugin-java/test/unit-test/text-blocks/_output.java
Text blocks are now split by lines when printing, with the "base indentation" removed, so that they are indented more logically by Prettier.
```java
System.out.println(
// leading comment
"""
abaoeu
euaoeu
aoeu
oaeu
abc""" // trailing comment
);
System.out.println(
"""
abaoeu
euaoeu
aoeu
oaeu
abc"""
);
}
}
```
```java
System.out.println(
// leading comment
"""
abaoeu
euaoeu
aoeu
oaeu
abc""" // trailing comment
);
System.out.println(
"""
abaoeu
euaoeu
aoeu
oaeu
abc"""
);
}
}
```
Closes #593
> feat: adjust text block indentation

- packages/prettier-plugin-java/src/printers/comments/handle-comments.ts
- packages/prettier-plugin-java/src/printers/expressions.ts
- packages/prettier-plugin-java/src/printers/printer-utils.ts
- packages/prettier-plugin-java/test/unit-test/binary_expressions/_input.java
- packages/prettier-plugin-java/test/unit-test/binary_expressions/_output.java
- packages/prettier-plugin-java/test/unit-test/expressions/_output.java
- packages/prettier-plugin-java/test/unit-test/sealed/_output.java
Binary expressions are now broken, indented, and wrapped with parentheses similar to the way Prettier JavaScript does. I tried to mimic the behavior of Prettier JavaScript as much as possible, except that this PR never removes parentheses around binary expressions, only adds them.
```java
2 / 3 * 10 / 2 + 2;
2 * 3 * 10 / 2 + 2;
a % 10 - 5;
a - 10 % 5;
a * b % 10;
a % b * 10;
a % 10 > 5;
1 << 2 >>> 3 >> 4;
1 << 2 + 3;
1 / 2 << 3;
x == y == z;
1 & 2 == 3;
if (aaaaaaaaaa + bbbbbbbbbb == cccccccccc + dddddddddd && eeeeeeeeee + ffffffffff == gggggggggg + hhhhhhhhhh || iiiiiiiiii) {}
if (a * b + c << d < e == f & g ^ h | i && j || k && l | m ^ n & o != p > q >> r - s / t) {}
if (aaaaaaaaaa + bbbbbbbbbb == cccccccccc + dddddddddd && eeeeeeeeee + ffffffffff == …
```
> feat: improve binary expression formatting

- packages/prettier-plugin-java/src/printers/printer-utils.ts
- packages/prettier-plugin-java/test/unit-test/blank_lines/_input.java
- packages/prettier-plugin-java/test/unit-test/blank_lines/_output.java
- packages/prettier-plugin-java/test/unit-test/comments/class/_output.java
- packages/prettier-plugin-java/test/unit-test/modifiers/_input.java
- packages/prettier-plugin-java/test/unit-test/modifiers/_output.java
Annotations placed after other modifiers on field declarations are no longer moved before all modifiers, allowing field declarations to follow JLS's formatting of type annotations the same way methods do.
```java
@AnotherAnnotation
private @Nullable Object object;
@AnotherAnnotation
private @Nullable Object method() {
return null;
}
}
```
```Java
@AnotherAnnotation
private @Nullable Object object;
@AnotherAnnotation
private @Nullable Object method() {
return null;
}
}
```
Fix #525
> fix: support JLS type annotations style

- packages/java-parser/src/utils.js
In JavaScript, it is a common mistake to check if a variable exists by directly referencing it. 
The correct way to do this is to use the `typeof` operator.
N/A
- fix #597
> fix(parser): Correctly detect `process`

- packages/prettier-plugin-java/README.md
I entered the incorrect main branch name in the banner URL I added to the plugin's README in #590. This PR fixes the branch name in that URL.
#590
> chore: fix plugin README's banner URL

- packages/prettier-plugin-java/src/printers/printer-utils.ts
- packages/prettier-plugin-java/test/unit-test/variables/_input.java
- packages/prettier-plugin-java/test/unit-test/variables/_output.java
Non-declarative assignment operations now indent properly again.
```java
fileSystemDetails =
FileHandlerDetails
.builder()
.fileSystemType(
EntityUtils.update(
entity.getFileSystemDetails().getFileSystemType(),
update.getFileSystemDetails().getFileSystemType()
)
);
aaaaaaaaaaaaaaaaa = bbbbbbbbbbbbbbbbb ? ccccccccccccccccc : ddddddddddddddddd;
aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa = bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb = ccccccccccccccccccccccccccccccccccccccc + ddddddddddddddddddddddddddddddddd;
}
}
```
```java
fileSystemDetails =
FileHandlerDetails
.builder()
.fileSystemType(
EntityUtils.update(
entity.getFileSystemDetails().getFileSystemType(),
update.getFileSystemDetails().getFileSystemType()
)
);
aaaaaaaaaaaaaaaaa = …
```
> fix: correct indentation of assignment operations

- .github/workflows/github-ci.yml
- packages/java-parser/scripts/clone-samples.js
- packages/java-parser/test/samples-spec.js
- packages/prettier-plugin-java/scripts/clone-samples.js
- packages/prettier-plugin-java/test/repository-test/core-test.ts
- packages/prettier-plugin-java/test/test-utils.ts
Upgrades the pipeline tests to JHipster 8, Java 17, and Node.js 18/20. Also upgraded GitHub Actions and repos used for testing to their latest versions (some were necessary upgrades, such as Spring Boot/Framework, others were not).
Closes #609
> chore: upgrade pipeline tests to JHipster 8, Java 17, and Node.js 18/20

- packages/java-parser/api.d.ts
- packages/java-parser/src/productions/classes.js
- packages/java-parser/src/productions/packages-and-modules.js
- packages/java-parser/src/productions/utils/class-body-types.js
- packages/java-parser/test/compilation-unit/unnamed-class-compilation-unit-spec.js
- packages/prettier-plugin-java/test/unit-test/unnamed-class-compilation-unit/_input.java
- packages/prettier-plugin-java/test/unit-test/unnamed-class-compilation-unit/_output.java
- packages/prettier-plugin-java/test/unit-test/unnamed-class-compilation-unit/unnamed-class-compilation-unit-spec.ts
```java
// Input
import com.toto.titi.Test;
import com.toto.titi.Toast;
class TestClass { static String greetings() { return "Hello world!"; } }
interface TestInterface { default String greetings() { return "Hello world!"; } }
;
String greeting() { return "Hello, World!"; }
void main() {
System.out.println(Test.greeting());
}
// Output
import com.toto.titi.Test;
import com.toto.titi.Toast;
class TestClass {
static String greetings() {
return "Hello world!";
}
}
interface TestInterface {
default String greetings() {
return "Hello world!";
}
}
String greeting() {
return "Hello, World!";
}
void main() {
System.out.println(Test.greeting());
}
```
Closes: #614
> Support unnamed class compilation unit

- packages/java-parser/scripts/clone-samples.js
Use same fix as @jtkiesel in #616 to avoid errors in demo-java-x repo (string templates)
> chore: use specific version for demo-java-x repo parsing

- packages/java-parser/src/comments.js
- packages/prettier-plugin-java/test/unit-test/prettier-ignore/block/_input.java
- packages/prettier-plugin-java/test/unit-test/prettier-ignore/block/_output.java
- packages/prettier-plugin-java/test/unit-test/prettier-ignore/prettier-ignore-spec.ts
When a block begins with `// prettier-ignore`, only the first statement is ignored, rather than the whole block.
```java
package tech.jhipster;
import java.util.Map;
public class StrangePrettierIgnore {
private StrangePrettierIgnore() {}
public static void drinkBeers() {
// prettier-ignore
Map<String, String> beers = Map.of(
"beer1", "Gulden Draak",
"beer2", "Piraat",
"beer3", "Kapittel"
);
System.out.println(beers); // not well formated here
}
}
```
```java
package tech.jhipster;
import java.util.Map;
public class StrangePrettierIgnore {
private StrangePrettierIgnore() {}
public static void drinkBeers() {
// prettier-ignore
Map<String, String> beers = Map.of(
"beer1", "Gulden Draak",
"beer2", "Piraat",
"beer3", "Kapittel"
);
System.out.println(beers); // not well formated here
}
}
``` …
> fix(parser): no longer ignore whole block when prettier-ignore at start

- README.md
More beginner-friendly documentation.
When coming from google-java-format --ASOP or palantir-java-format, it is not that obvious how to use prettier-java. Adding some lines of documentation makes it obvious (and thus this project is more beginner-friendly)
Fixes https://github.com/jhipster/prettier-java/issues/495.
> Add information on how to change indent

- README.md
When following the README, before this PR:
```
[error] No parser could be inferred for file: src/main/java/com/natoboram/switcheroo/Main.java
```
With this PR:
```
src/main/java/com/natoboram/switcheroo/Main.java 4ms
```
Fixes https://github.com/jhipster/prettier-java/issues/508
> Add hint on configuration

- packages/java-parser/api.d.ts
- packages/java-parser/src/index.js
Provide an entrypoint that exposes both the CST and the underlying token array.
The token array could also be accessed through the `parser` object, which we could export instead, but that seems like an internal implementation detail which perhaps shouldn't be part of the API.
Finally, we could consider exporting the lexer, but then if I want to get both the CST and the tokens I have to lex twice, which seems wasteful.
> java-parser: New entrypoint `lexAndParse` to return both tokens and CST.

- packages/prettier-plugin-java/src/printers/blocks-and-statements.ts
- packages/prettier-plugin-java/test/unit-test/empty_statement/_output.java
- packages/prettier-plugin-java/test/unit-test/sealed/_output.java
Non-block if/else statements are now kept on their own lines, like Prettier JavaScript does. This aligns Prettier Java with the Checkstyle config that it provides.
```java
if (test); else {
System.out.println("one");
}
if (test); else;
if (this instanceof Circle) return "Circle: " + area(); else if (
this instanceof Rectangle
) return "Rectangle: " + area(); else if (
this instanceof RightTriangle
) return "Triangle: " + area();
}
}
```
```java
if (test);
else {
System.out.println("one");
}
if (test);
else;
if (this instanceof Circle) return "Circle: " + area();
else if (this instanceof Rectangle) return "Rectangle: " + area();
else if (this instanceof RightTriangle) return "Triangle: " + area();
}
}
```
Closes #631
> fix: break between non-block if/else statements

- packages/java-parser/api.d.ts
- packages/java-parser/src/productions/classes.js
- packages/java-parser/test/bugs-spec.js
- packages/prettier-plugin-java/src/printers/classes.ts
- packages/prettier-plugin-java/test/unit-test/bug-fixes/_input.java
- packages/prettier-plugin-java/test/unit-test/bug-fixes/_output.java
Fixes some issues with constructor receiver parameters, and added support for method receiver parameters.
```java
class Currency {
Currency(Currency this) {}
Currency(Currency this, Currency other) {}
Currency(@AnnotatedUsage Currency this, Currency other) {}
Currency(@AnnotatedUsage Currency this, String aaaaaaaaaa, String bbbbbbbbbb) {}
String getCode(Currency this) {}
int compareTo(Currency this, Currency other) {}
int compareTo(@AnnotatedUsage Currency this, Currency other) {}
int compareTo(@AnnotatedUsage Currency this, String aaaaaaaaaa, String bbbbbbbbbb) {}
class Inner {
Inner(Currency Currency.this) {}
String getCode(Currency Currency.this) {}
}
}
```
```java
class Currency {
Currency(Currency this) {}
Currency(Currency this, Currency other) {}
Currency(@AnnotatedUsage Currency …
```
> fix: constructor and method receiver parameter

- packages/prettier-plugin-java/src/printers/printer-utils.ts
- packages/prettier-plugin-java/test/unit-test/variables/_input.java
- packages/prettier-plugin-java/test/unit-test/variables/_output.java
Long assignment operations are now consistently broken after equals between variable declarations and binary expressions. Assignment operations now avoid breaking after the equals, the way variable declarations do. This also aligns the formatting of these lines more closely to the way Prettier JavaScript does.
```java
foo = new Foo("aaaaaaaaaaaaaaaaaaaa", "bbbbbbbbbbbbbbbbbbbb", "cccccccccccccccccccc", "dddddddddddddddddddd", "eeeeeeeeeeeeeeeeeeee", "ffffffffffffffffffff");
final Foo bar = new Foo("aaaaaaaaaaaaaaaaaaaa", "bbbbbbbbbbbbbbbbbbbb", "cccccccccccccccccccc", "dddddddddddddddddddd", "eeeeeeeeeeeeeeeeeeee", "ffffffffffffffffffff");
}
}
```
```java
foo = new Foo(
"aaaaaaaaaaaaaaaaaaaa",
"bbbbbbbbbbbbbbbbbbbb", …
```
> fix: consistent break after equals

- .eslintignore
- package.json
This reverts commit ac1a02b2e9179ecfbbd25e9afd0a24933fa33424, which broke the CI build, as it made ESLint attempt to lint TypeScript files, and we do not currently configure ESLint to use the TypeScript parser or use any TypeScript config packages.
> Revert "chore: fix lint script"

- packages/prettier-plugin-java/src/options.js
- website/src/pages/playground/index.tsx
Adds `es5` as a valid `trailingComma` option, to align with the Prettier option.
Closes #652
> fix: add es5 as trailingComma option

- packages/prettier-plugin-java/src/printers/classes.ts
- packages/prettier-plugin-java/src/printers/comments/handle-comments.ts
- packages/prettier-plugin-java/src/printers/expressions.ts
- packages/prettier-plugin-java/src/printers/interfaces.ts
- packages/prettier-plugin-java/src/printers/printer-utils.ts
- packages/prettier-plugin-java/src/utils/printArgumentListWithBraces.ts
- packages/prettier-plugin-java/test/unit-test/comments/comments-blocks-and-statements/end-of-block/_output.java
- packages/prettier-plugin-java/test/unit-test/lambda/_input.java
- packages/prettier-plugin-java/test/unit-test/lambda/_output.java
- packages/prettier-plugin-java/test/unit-test/unnamed-variables-and-patterns/_output.java
Argument "hugging" is now aligned much more closely with Prettier JavaScript. Specifically, lambdas without blocks are "huggable" again.
```java
class T {
public Semver getMaven() {
return describe()
.map(v -> null == v ? PRE_VERSION : v)
.map(Semver::coerce)
.map(v -> Objects.equals(v.getVersion(), PRE_VERSION) ? v.withPreRelease(SNAPSHOT) : v)
.map(
v ->
v
.getPreRelease()
.stream()
.filter(p -> p.matches("^\\d+-+g\\p{XDigit}{7}$"))
.findFirst()
.map(p -> v.withClearedPreRelease().withPreRelease(SNAPSHOT).withBuild(p))
.orElse(v)
)
.map(v -> new MavenSemver(v.getVersion()))
.get();
}
void t() {
aaaaaaaaaaaaaaaaaaaaaaaa((bbbbbbbbbbbbbbbbbbbbbbbb, cccccccccccccccccccccccc, dddddddddddddddddddddddd) -> eeeeeeeeeeeeeeeeeeeeeeee.ffffffffffffffffffffffff());
a.b(c -> d -> …
```
> fix: hug lambdas without blocks

- packages/prettier-plugin-java/src/printers/comments/handle-comments.ts
- packages/prettier-plugin-java/test/repository-test/core-test.ts
- packages/prettier-plugin-java/test/test-utils.ts
- packages/prettier-plugin-java/test/unit-test/comments/comments-spec.ts
- packages/prettier-plugin-java/test/unit-test/comments/expression/_input.java
- packages/prettier-plugin-java/test/unit-test/comments/expression/_output.java
Binary expressions with comments before the first operator no longer fail to print.
```java
0 //
+ 1;
}
}
```
```java
0 + //
1;
}
}
```
Closes #685
> fix: print comment before first binary operator without failing

- packages/prettier-plugin-java/src/printers/blocks-and-statements.ts
- packages/prettier-plugin-java/test/unit-test/comments/comments-blocks-and-statements/complex/_output.java
- packages/prettier-plugin-java/test/unit-test/comments/comments-blocks-and-statements/labeled-statement/_input.java
- packages/prettier-plugin-java/test/unit-test/comments/comments-blocks-and-statements/labeled-statement/_output.java
Labeled statements are now printed with a space between the label and the statement.
```java
void labeledForLoop() {
label:for (int i = 0; i < 1; i++) {}
}
void labeledBlockStatement() {
label:{
example();
}
}
}
```
```java
void labeledForLoop() {
label: for (int i = 0; i < 1; i++) {}
}
void labeledBlockStatement() {
label: {
example();
}
}
}
```
Closes #686
> fix: add whitespace between label and statement

- packages/prettier-plugin-java/src/printers/expressions.ts
- packages/prettier-plugin-java/src/printers/printer-utils.ts
- packages/prettier-plugin-java/test/unit-test/binary_expressions/_input.java
- packages/prettier-plugin-java/test/unit-test/binary_expressions/_output.java
Assignment expressions with boolean expression righthand sides no longer break/indent poorly, and assignment expressions in general are now printed the same way as variable declarations.
```java
double availability12 =
(double) successfulCount / (successfulCount + failureCount);
availability12 = (double) successfulCount /
(successfulCount + failureCount);
var lineLengthInAssignmentMoreThanPrintWidth =
"1234567890" +
"1234567890" +
"1234567890" +
"1234567890" +
"1234567890" +
"1234567890";
lineLengthInAssignmentMoreThanPrintWidth = "1234567890" +
"1234567890" +
"1234567890" +
"1234567890" +
"1234567890" +
"1234567890";
aaaaaaaaaa +=
bbbbbbbbbbb +
ccccccccccc +
ddddddddddd +
eeeeeeeeee +
ffffffffff +
gggggggggg;
aaaaaaaaaa %=
bbbbbbbbbbb +
ccccccccccc + …
```
> fix: break and indent assignments like declarations

- packages/prettier-plugin-java/package.json
This PR moves prettier from `dependencies` to `devDependencies` and adds it to `peerDependencies`.
> fix: move prettier from `dependencies` to `devDependencies`

- website/src/components/CodeEditor/index.tsx
- website/src/pages/playground/index.tsx
Website's playground no longer displays an empty formatted (read-only) editor when navigating to another page and then back to the playground.
There seems to be a bug in Monaco Editor for React where in certain situations, updating its value prop immediately after rendering the component for the first time causes it to continue rendering the original value. I verified that the component was being passed the formatted code as its value 2nd, after initially setting it to empty, and yet it was rendering empty.
This fix works around that apparent bug by no longer rendering the component at all on the initial render, meaning it will only render the formatted (read-only) editor after Prettier formats it.
> fix(website): prevent playground formatted editor from being empty on navigation

- .github/workflows/github-ci.yml
- packages/java-parser/api.d.ts
- packages/java-parser/scripts/generate-signature.js
- packages/java-parser/scripts/single-sample-runner.js
- packages/java-parser/src/productions/classes.js
- packages/java-parser/test/classes-spec.js
- packages/java-parser/test/pattern-matching/pattern-matching-spec.js
- packages/prettier-plugin-java/src/printers/classes.ts
This piece of code was failing as the java-parser tried to parse `String otherName, String[] otherContent` as a variable declaration list instead of component pattern list
I added backtrack lookahead which fixed the issue but will see if we can avoid it completely.
```java
// Input
public class Foo {
public void bar() {
if (!(obj instanceof Project(String otherName, String[] otherContent))) {
return false;
}
}
}
```
#707
> fix(707): do not throw if the record-pattern contains dims

- packages/prettier-plugin-java/package.json
Support for require is restored for compatibility with the Prettier VS Code plugin.
Closes #711
> fix: restore require support for VS Code compatibility

- packages/prettier-plugin-java/src/printers/expressions.ts
- packages/prettier-plugin-java/test/unit-test/lambda/_input.java
- packages/prettier-plugin-java/test/unit-test/lambda/_output.java
The bodies of lambdas used as hugged arguments are now broken when the closing parenthesis of the enclosing argument list is wrapped.
```java
aaaaaaaaaa(bbbbbbbbbb -> cccccccccc("123456789012345678901234567890123456"));
aaaaaaaaaa(bbbbbbbbbb -> "123456789012345678901234567890123456789012345678");
}
}
```
```java
aaaaaaaaaa(bbbbbbbbbb ->
"123456789012345678901234567890123456789012345678"
);
aaaaaaaaaa(bbbbbbbbbb ->
cccccccccc("123456789012345678901234567890123456")
);
}
}
```
Closes #718
> fix: break hugged lambda body when closing parenthesis wraps

- packages/java-parser/api.d.ts
- packages/java-parser/src/productions/blocks-and-statements.js
- packages/java-parser/src/productions/classes.js
- packages/java-parser/src/productions/expressions.js
- packages/java-parser/test/pattern-matching/pattern-matching-spec.js
- packages/prettier-plugin-java/src/printers/classes.ts
There exists some ambiguity in the parser within comma-separated `TypePattern`s, because `TypePattern` contains a `VariableDeclaratorList`, which is comma-separated `VariableDeclarator`s. The parser cannot currently determine where the `VariableDeclaratorList` ends and the next `TypePattern` begins. This was previously realized in #707, within `ComponentPatternList`, and is now experienced in #733, within `SwitchLabel`.
I realized that the JLS specifically mentions semantic restrictions that make it easy to resolve this ambiguity. From [14.30.1. Kinds of Patterns](https://docs.oracle.com/javase/specs/jls/se24/html/jls-14.html#jls-14.30.1) (emphasis mine):
> The rules for a local variable declared in a type pattern are specified in …
> fix: limit TypePattern's VariableDeclaratorList to a single VariableDeclarator

- packages/prettier-plugin-java/scripts/update-test-output.js
- packages/prettier-plugin-java/test/test-utils.ts
- packages/prettier-plugin-java/test/unit-test/binary_expressions/binary_expressions-spec.ts
- packages/prettier-plugin-java/test/unit-test/binary_expressions/operator-position-end/.prettierrc.json
- packages/prettier-plugin-java/test/unit-test/binary_expressions/operator-position-start/.prettierrc.json
- packages/prettier-plugin-java/test/unit-test/require-pragma/format-pragma/.prettierrc.json
- packages/prettier-plugin-java/test/unit-test/require-pragma/invalid-pragma/.prettierrc.json
- packages/prettier-plugin-java/test/unit-test/require-pragma/prettier-pragma/.prettierrc.json
- packages/prettier-plugin-java/test/unit-test/require-pragma/require-pragma-spec.ts
Before this change, checking out the project and running update-test-outputs would make changes to the test outputs.
```
❯ npm run build && npm run update-test-outputs
❯ git status
HEAD detached at upstream/main
Changes not staged for commit:
(use "git add <file>..." to update what will be committed)
(use "git restore <file>..." to discard changes in working directory)
modified:   packages/prettier-plugin-java/test/unit-test/binary_expressions/operator-position-start/_output.java
modified:   packages/prettier-plugin-java/test/unit-test/require-pragma/invalid-pragma/_output.java
no changes added to commit (use "git add" and/or "git commit -a")
```
The change here is to use the test-specific configuration while recording tests. With this change, running npm run update-test-outputs doesn't …
> Fix update-test-outputs script to use test-specific prettier options.

- package.json
- packages/prettier-plugin-java/tsconfig.json
Do not generate relative path in generated types.
Fixes https://github.com/jhipster/prettier-java/issues/746
> chore: fix generated types

- packages/prettier-plugin-java/src/printers/helpers.ts
- packages/prettier-plugin-java/test/unit-test/types/_input.java
- packages/prettier-plugin-java/test/unit-test/types/_output.java
Class types with type arguments followed by a dot (`.`) are printed in that order, rather than moving the dot before the type arguments.
```java
@A B.C<D>.@E @F G.H h;
}
```
```java
@A
B.C<D>.@E @F G.H h;
}
```
Closes #752
> fix: print class type arguments and dots in the proper order

- packages/prettier-plugin-java/src/printers/blocks-and-statements.ts
- packages/prettier-plugin-java/test/unit-test/try_catch/_input.java
- packages/prettier-plugin-java/test/unit-test/try_catch/_output.java
Reverts the connection of trailing semicolon printing (in ResourceSpecification) to the `trailingComma` option (which was done in #731). This is a bit of an edge case, and it isn't at all intuitive that an option named `trailingComma` would also control whether a trailing semicolon would be printed in this case. The optional trailing semicolon will now be left as-is (printed if it exists, omitted if not), as it used to be.
```java
void multiResourceTry() {
try (FirstResource firstResource = new FirstResource(); SecondResource secondResource = new SecondResource()) {
return br.readLine();
} catch (ArithmeticException | ArrayIndexOutOfBoundsException e) {
System.out.println("Warning: Not breaking multi exceptions");
}
}
void multiResourceTryWithTrailingSemi() {
try ( …
```
> fix: revert connection of trailing semicolon to trailingComma option

- website/docusaurus.config.ts
Website's edit URLs are corrected to point to the proper source paths so that they no longer resolve to a 404 page.
> docs: fix website edit URLs

- packages/prettier-plugin-java/src/printers/blocks-and-statements.ts
- packages/prettier-plugin-java/src/printers/expressions.ts
- packages/prettier-plugin-java/src/printers/helpers.ts
- packages/prettier-plugin-java/test/unit-test/if/_input.java
- packages/prettier-plugin-java/test/unit-test/if/_output.java
Our `call` helper is implemented by calling AstPath's `map` method and indexing into the returned array. This PR removes the ability to index to anything other than `0`, to prevent it from being used to execute individual calls to individual path indices, which was causing all indices to be re-processed each time `call` was executed, which in some cases (such as long if-else statement chains) was causing printer functions to be executed an exponential number of times (according to the number of if-else statements in the chain). Anything that was previously using the indexing feature of `call` is now updated to either use the `map` helper once, and index into the results, or use `AstPath.call` directly, which is a bit more verbose, but it's a rare use-case in our printer to begin with. …
> fix: eliminate repeated printer function execution from our naively-implemented 'call' helper

- packages/prettier-plugin-java/src/printers/expressions.ts
- packages/prettier-plugin-java/test/unit-test/lambda/_input.java
- packages/prettier-plugin-java/test/unit-test/lambda/_output.java
- packages/prettier-plugin-java/test/unit-test/template-expression/_output.java
Certain method invocations containing lambda arguments with bodies no longer have their arguments double-indented.
This includes a minor change to templates as well, but those were a preview feature and are no longer supported by Java, plus the change makes the formatting of them more consistent.
```java
A.b().c(() -> {
return d;
});
this.a(
aaaaaaaaaaaaaaaaaaaaaaaaaa,
bbbbbbbbbbbbbbbbbbbbbbbbbb,
cccccccccccccccccccccccccc,
dddddddddddddddddddddddddd,
e -> {
return f;
}
);
}
}
```
```java
A.b().c(() -> {
return d;
});
this.a(
aaaaaaaaaaaaaaaaaaaaaaaaaa,
bbbbbbbbbbbbbbbbbbbbbbbbbb,
cccccccccccccccccccccccccc,
dddddddddddddddddddddddddd,
e -> {
return f;
}
);
}
}
```
Closes #760
Closes #764
> fix: correct indentation of some method argument lists containing lambda bodies
