.prettierrc
PREVIEW.md
src/printer.js
tests/constructors/__snapshots__/jsfmt.spec.js.snap
tests/constructors/constructors.java
tests/generic_class/__snapshots__/jsfmt.spec.js.snap
tests/generic_invocation/__snapshots__/jsfmt.spec.js.snap
tests/instantiation/__snapshots__/jsfmt.spec.js.snap
tests/instantiation/instantiation.java
tests/instantiation/jsfmt.spec.js
tests/lambda/__snapshots__/jsfmt.spec.js.snap
tests/member_chain/__snapshots__/jsfmt.spec.js.snap
tests/variables/__snapshots__/jsfmt.spec.js.snap

Better argument list

---

src/printer.js
tests/while/__snapshots__/jsfmt.spec.js.snap
tests/while/while.java

Fixes https://github.com/thorbenvh8/prettier-java/issues/56

Handle do while statements

---

src/printer.js
tests/variables/__snapshots__/jsfmt.spec.js.snap
tests/variables/variables.java

Fixes https://github.com/thorbenvh8/prettier-java/issues/59

Handle oct literals

---

packages/java-parser/README.md

docs(java-parser): fix install instructions

---

packages/java-parser/package.json

Instead, link to somewhere that exists.

npm repo link is a 404

---

packages/java-parser/src/productions/blocks-and-statements.js
packages/java-parser/test/samples-spec.js

Fix missing semiColon in throwStatement (https://docs.oracle.com/javase/specs/jls/se11/html/jls-14.html#jls-ThrowStatement) continueStatement (https://docs.oracle.com/javase/specs/jls/se11/html/jls-14.html#jls-ContinueStatement) and returnStatement (https://docs.oracle.com/javase/specs/jls/se11/html/jls-14.html#jls-ReturnStatement) specs

Fix block and statements

---

packages/prettier-plugin-java/scripts/update-test-output.js
packages/prettier-plugin-java/src/printers/arrays.js
packages/prettier-plugin-java/src/printers/classes.js
packages/prettier-plugin-java/src/printers/lexical-structure.js
packages/prettier-plugin-java/src/printers/names.js
packages/prettier-plugin-java/src/printers/packages-and-modules.js
packages/prettier-plugin-java/src/printers/printer-utils.js
packages/prettier-plugin-java/src/printers/types-values-and-variables.js
packages/prettier-plugin-java/test/hello-world/_input.java
packages/prettier-plugin-java/test/hello-world/_output.java

WIP on classes and types-values-and-variables

WIP: Cst printer

---

packages/java-parser/scripts/clone-samples.js
packages/java-parser/test/samples-spec.js

I've added sampling data for testing purposes. It mainly contains jhipster-generated applications and jhipster-related repositories to make sure it can be ran with JHipster.

Reinforced test sampling data and added repo's to parse

---

packages/java-parser/scripts/unicode.js
packages/java-parser/src/unicodesets.js

Some change in the generated file in order to make it clear from #170

unicode optimization: small upgrades

---

packages/prettier-plugin-java/package.json
packages/prettier-plugin-java/scripts/clone-samples.js
packages/prettier-plugin-java/test/prettify-test.js
packages/prettier-plugin-java/test/test-utils.js

I have added a skeleton of tests, it clone repositories and performs prettier on all java files and then try to compile to check if the project is still semantically valid.
We can later add more repositories.

improve cstprinter test

---

azure-pipelines.yml

Just for init and configuring the organization
Related to https://github.com/jhipster/prettier-java/issues/195

CI: add default azure-pipelines for init

---

packages/prettier-plugin-java/src/printers/classes.js
packages/prettier-plugin-java/src/printers/interfaces.js
packages/prettier-plugin-java/src/printers/printer-utils.js
packages/prettier-plugin-java/test/unit-test/classes/_input.java
packages/prettier-plugin-java/test/unit-test/classes/_output.java
packages/prettier-plugin-java/test/unit-test/interface/_input.java
packages/prettier-plugin-java/test/unit-test/interface/_output.java

Refactor the way we handle classBody declarations and apply the same logic to interface body declarations.
Fix #220

Fix interfaces user blank lines

---

packages/prettier-plugin-java/src/printers/blocks-and-statements.js
packages/prettier-plugin-java/test/unit-test/annotation_type_declaration/_input.java
packages/prettier-plugin-java/test/unit-test/annotation_type_declaration/_output.java
packages/prettier-plugin-java/test/unit-test/comments/class/_input.java
packages/prettier-plugin-java/test/unit-test/comments/class/_output.java

grouped annotation in a single line when local variable is defined

---

packages/java-parser/src/comments.js
packages/java-parser/src/index.js
packages/java-parser/src/parser.js
packages/prettier-plugin-java/src/cst-printer.js
packages/prettier-plugin-java/src/printer.js
packages/prettier-plugin-java/src/printers/packages-and-modules.js
packages/prettier-plugin-java/src/printers/printer-utils.js
packages/prettier-plugin-java/test/unit-test/prettier-ignore/classDeclaration/_input.java
packages/prettier-plugin-java/test/unit-test/prettier-ignore/classDeclaration/_output.java
packages/prettier-plugin-java/test/unit-test/prettier-ignore/method/_input.java
packages/prettier-plugin-java/test/unit-test/prettier-ignore/method/_output.java
packages/prettier-plugin-java/test/unit-test/prettier-ignore/multiple-ignore/_input.java
packages/prettier-plugin-java/test/unit-test/prettier-ignore/multiple-ignore/_output.java
packages/prettier-plugin-java/test/unit-test/prettier-ignore/prettier-ignore-spec.js

Prettier ignore support

---

packages/prettier-plugin-java/src/printers/prettier-builder.js
packages/prettier-plugin-java/test/unit-test/comments/class/_input.java
packages/prettier-plugin-java/test/unit-test/comments/class/_output.java
packages/prettier-plugin-java/test/unit-test/comments/edge/_output.java
packages/prettier-plugin-java/test/unit-test/comments/interface/_output.java

Fix javadoc indentation

---

azure-pipelines.yml

Related to https://github.com/jhipster/generator-jhipster/pull/10173

Update Node version to 10.16.1

---

azure-pipelines.yml

Related to https://github.com/jhipster/generator-jhipster/pull/10236

Update Node version to 10.16.3

---

packages/java-parser/package.json
packages/prettier-plugin-java/package.json
yarn.lock

Add missing lodash dependency

---

packages/java-parser/src/parser.js

refactor backtracking fix

---

azure-pipelines.yml

Related to https://github.com/jhipster/generator-jhipster/pull/10707

update Node version to v12.13.0, replace Node v8 test with Node v13

---

packages/prettier-plugin-java/src/cst-printer.js
packages/prettier-plugin-java/src/printers/comments.js

fix: prettier-ignore when visit called with array

---

.eslintignore
.eslintrc.yml
packages/java-parser/scripts/clone-samples.js
packages/java-parser/src/tokens.js
packages/prettier-plugin-java/scripts/clone-samples.js
packages/prettier-plugin-java/src/printers/arrays.js
packages/prettier-plugin-java/src/printers/blocks-and-statements.js
packages/prettier-plugin-java/src/printers/classes.js
packages/prettier-plugin-java/src/printers/expressions.js
packages/prettier-plugin-java/src/printers/interfaces.js
packages/prettier-plugin-java/src/printers/lexical-structure.js
packages/prettier-plugin-java/src/printers/names.js
packages/prettier-plugin-java/src/printers/packages-and-modules.js
packages/prettier-plugin-java/src/printers/types-values-and-variables.js

Remove eslint-disable comments to improve code quality

chores: enforce eslint rule to avoid unused variables

---

packages/prettier-plugin-java/test/unit-test/comments/comments-only/_input.java
packages/prettier-plugin-java/test/unit-test/comments/comments-only/_output.java

Related to https://github.com/jhipster/generator-jhipster/pull/11048

Update Copyright Headers for 2020

---

packages/prettier-plugin-java/src/printers/arrays.js
packages/prettier-plugin-java/src/printers/blocks-and-statements.js
packages/prettier-plugin-java/src/printers/classes.js
packages/prettier-plugin-java/src/printers/comments.js
packages/prettier-plugin-java/src/printers/interfaces.js
packages/prettier-plugin-java/src/printers/packages-and-modules.js
packages/prettier-plugin-java/src/printers/printer-utils.js
packages/prettier-plugin-java/test/unit-test/comments/comments-blocks-and-statements/end-of-block/_input.java
packages/prettier-plugin-java/test/unit-test/comments/comments-blocks-and-statements/end-of-block/_output.java
packages/prettier-plugin-java/test/unit-test/formatter-on-off/method/_output.java

Indent comment based on the bloc they are in

---

azure-pipelines.yml

Related with https://github.com/jhipster/generator-jhipster/pull/11067

Update node to version 12.14.0 LTS

---

packages/prettier-plugin-java/src/cst-printer.js
packages/prettier-plugin-java/src/printers/blocks-and-statements.js
packages/prettier-plugin-java/src/printers/classes.js
packages/prettier-plugin-java/src/printers/comments/comments-utils.js
packages/prettier-plugin-java/src/printers/comments/format-comments.js
packages/prettier-plugin-java/src/printers/comments/handle-comments.js
packages/prettier-plugin-java/src/printers/expressions.js
packages/prettier-plugin-java/src/printers/interfaces.js
packages/prettier-plugin-java/src/printers/lexical-structure.js
packages/prettier-plugin-java/src/printers/names.js
packages/prettier-plugin-java/src/printers/packages-and-modules.js
packages/prettier-plugin-java/src/printers/prettier-builder.js
packages/prettier-plugin-java/src/printers/printer-utils.js
packages/prettier-plugin-java/src/printers/types-values-and-variables.js

Refactor to regroup comments utilities in one folder

refactor: move comments utils

---

CHANGELOG.md

🚀 Update Changelog for 0.7.0 release! 🚀

Update Changelog to v0.7.0

---

.prettierrc.yaml
README.md
docs/advanced_usage.md
packages/java-parser/src/productions/blocks-and-statements.js
packages/java-parser/src/productions/classes.js
packages/prettier-plugin-java/src/printers/blocks-and-statements.js

Add docs on how to use the plugin
@pascalgrimaud I would like to have your feedback on this when you have time :)

docs: add docs on how to use the plugin

---

azure-pipelines.yml

Related to https://github.com/jhipster/generator-jhipster/pull/11328

Upgrade to Node.js 12.16.0 LTS

---

packages/prettier-plugin-java/package.json

chore: update prettier dependency to 1.19.1

---

azure-pipelines.yml

Related to https://github.com/jhipster/generator-jhipster/pull/11428

Upgrade to Node.js 12.16.1 LTS

---

packages/java-parser/README.md

Update README code sample to latest version of the parser
Fix #374

chore: fix README code sample

---

.github/workflows/github-ci.yml
CONTRIBUTING.md
README.md

```java
// Input
// Output
```

chores: Improving documentation

---

README.md

Close #292
```java
// Input
// Output
```

doc: prettier-java maven plugin

---

.github/workflows/github-ci.yml

```java
// Input
// Output
```

feat: skip ci option

---

packages/java-parser/api.d.ts
packages/java-parser/package.json
packages/java-parser/scripts/generate-signature.js

Generate a .d.ts signature file for parser
#416

feat: generate parser Typescript signature

---

.github/workflows/github-ci.yml

related to https://github.com/jhipster/generator-jhipster/issues/12877

Add Node 14 to CI

---

package.json
packages/java-parser/package-lock.json
packages/prettier-plugin-java/package-lock.json
packages/prettier-plugin-java/package.json
yarn.lock

chore: update dependencies

---

docs/advanced_usage.md

```java
// Input
// Output
```

doc: add documentation when importing on Nuxt Project

---

packages/prettier-plugin-java/package.json
packages/prettier-plugin-java/src/parser.js
packages/prettier-plugin-java/src/printer.js
packages/prettier-plugin-java/src/printers/classes.ts
packages/prettier-plugin-java/src/printers/interfaces.ts
packages/prettier-plugin-java/src/printers/prettier-builder.ts
packages/prettier-plugin-java/src/printers/printer-utils.ts
yarn.lock

Update prettier dependency to v3
#557

Update to prettier 3

---

packages/java-parser/package.json
packages/prettier-plugin-java/package.json

fixes https://github.com/jhipster/prettier-java/issues/663

add exports to package.json

---

docs/advanced_usage.md

Update **trailingComma** option
- https://prettier.io/docs/en/options.html#trailing-commas

Update trailingComma option on advanced_usage.md

---

README.md
docs/advanced_usage.md

Correct for latest IntelliJ and node versions, add formatting and minor clarification.
- Emphasized that IDE configuration is on the advanced configuration page
- Updated IntelliJ configuration to be compatible with current releases of IntelliJ
- Added notes regarding prettier installation
- Minor grammatical and formatting updates

(doc) Updated advanced_usage.md with current working configuration for IntelliJ

---

packages/prettier-plugin-java/index.d.ts
packages/prettier-plugin-java/package.json

This PR adds typescript support to package `prettier-plugin-java`.

feat: add typescript support to `prettier-plugin-java`

---

website/package.json
website/yarn.lock

Website dependencies are updated to their latest versions.

chore(website): update dependencies

---

CHANGELOG.md
package.json
packages/prettier-plugin-java/test/test-utils.ts
website/package.json
website/yarn.lock
yarn.lock

Run CI to check if everything is ok before starting release

Prepare 2.6.1 release

---

website/package.json
website/src/components/CodeEditor/index.tsx
website/src/pages/playground/index.tsx
website/yarn.lock

Website's playground editors now have rulers that visualize the current `printWidth` value.

docs: add rulers to playground editors

---

packages/prettier-plugin-java/src/options.ts
website/package.json
website/src/components/CodeEditor/index.tsx
website/src/pages/playground/index.tsx
website/yarn.lock

`arrowParens` and `experimentalOperatorPosition` options are added to the plugin's options object and the website's playground. Docusaurus and other website dependencies are updated to their latest versions.

docs: Add arrowParens and experimentalOperatorPosition options to plugin and website playground

---

.prettierignore
lerna.json

Adds json schema to learn.json

chore: run lerna repair
